dist: xenial

addons:
  postgresql: 9.6
  # TODO: Add mysql addon as well

services:
  - mysql
  - rabbitmq

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
  - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
  - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz"
  - ES_HOST=127.0.0.1
  matrix:
  - REQUIREMENTS=release EXTRAS=all,postgresql,tests ES=$ES6_DOWNLOAD_URL SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
  - REQUIREMENTS=release EXTRAS=all,postgresql,tests-es7 ES=$ES7_DOWNLOAD_URL  OAREPO_VERSION=3.2.0 SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI

python:
- '3.7'
- '3.8'

before_install:
- travis_retry pip install --upgrade pip setuptools py
- "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
- "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
- "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
- cat .travis-release-requirements.txt

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "T2x/XM7AnK96bIYua1MOKKTOd9fKSNpn1pvzmyFHXcpJsv4WZ2IOFs4i/oz8JvuUo3bsBOw0nWgJbO+DDtwqFeDvqWmIvbEFtcHPc/ng08itPYfAGJLH6AMo2N1jKXPBvMuprAbOKAEGdDV2FY6sw8wLLZhu+er5zuVyBcvzPDeCXMAUqrXlg6Uzm6YkmYzu37OMbMaKB3V/lzk/+icfmqp5AMI5kh2U4FOp1fHixzoJdDu38Lq95unNHvAv7ERS0VLx3vNZYBhnevblDIlP5fHq48YTbt00k30ikK0wmzACl0sOjIwmVYg0meREgzuVaOcIyFPmflK58Ne9EfcMA/YTDUebVnbxXhtmO5emI1TMeB9J1El01ahu28/H0deqM2lqEGHHhlJDvlSxIhY9p/uGzI/WgJPMgUZHUagjJ1+WtvVMyp+TmABoK5R7YbQIl5uRQTP4FCO6u5AE3VKQoRKJHRjzl6JEENLXodstQSO7EXvZWHyHgY/24lOW3Ft11nZwllkOAezdELY/Bb6wm5RumCliNtJe/PycG66cpUTDspnfARTrzKpxKwYZFj8yoBznFEtmYS36tM/xTxU7zYYtX0S+woinoB91p+zB72rtm7KcvQoCe86HBrhw8cFUSVsLNMpUxpIyVC5cKiA3MkSR3wI78MyJUjOBeOFi20I="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
